### ISSUE TITLE
服务器插件加载报错

### ISSUE THREAD

**Issue by KotoriK** [ParaParty/JustChat#14]
运行环境
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
VexView 2.2.jar已加载
Spigot MCv12.2

启动时加载插件出错。后台输出如下：
[13:37:05 INFO]: [MultiRobot] Enabling MultiRobot v1.2.0
[13:37:05 INFO]: [MultiRobot] 加载中...
[13:37:05 INFO]: [MultiRobot] 正在连接到服务器
[13:37:05 ERROR]: Error occurred while enabling MultiRobot v1.2.0 (Is it up to date?)
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(Unknown Source) ~[?:1.8.0_201]
        at cn.endymx.multirobot.LoadClass.onEnable(LoadClass.java:50) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[Core.jar:git-Paper-1298]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [Core.jar:git-Paper-1298]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [Core.jar:git-Paper-1298]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:383) [Core.jar:git-Paper-1298]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:332) [Core.jar:git-Paper-1298]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [Core.jar:git-Paper-1298]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [Core.jar:git-Paper-1298]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [Core.jar:git-Paper-1298]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [Core.jar:git-Paper-1298]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [Core.jar:git-Paper-1298]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
[13:37:05 INFO]: [MultiRobot] Disabling MultiRobot v1.2.0
[13:37:05 INFO]: [MultiRobot] 关闭中...

**Comment by KotoriK** [comment]
是指MC1.12.2版本的Spigot

**Comment by ExerciseBook** [comment]
@endymx 你怎么还不来回复啊。。。。。

**Comment by zhzhongshi** [comment]
``` log
[20:54:51 INFO]: [MultiRobot] Enabling MultiRobot v1.2.0
[20:54:51 INFO]: [MultiRobot] 加载中...
[20:54:51 INFO]: [MultiRobot] 正在连接到服务器
[20:54:51 ERROR]: Error occurred while enabling MultiRobot v1.2.0 (Is it up to d
ate?)
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1931) ~[?:1.8.0_131]
        at cn.endymx.multirobot.LoadClass.onEnable(LoadClass.java:50) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[P
aper-1.12.2-b1618.jar:git-Paper-1618]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:316) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:405) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.
java:395) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer
.java:344) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:8
08) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at org.bukkit.Bukkit.reload(Bukkit.java:559) ~[Paper-1.12.2-b1618.jar:gi
t-Paper-1618]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:
55) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:15
2) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServ
er.java:685) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerCo
nnection.java:1492) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.jav
a:1297) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.jav
a:45) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.jav
a:5) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMain
Thread$0(PlayerConnectionUtils.java:14) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]

        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1) ~[?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_13
1]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[Paper-1.
12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:
850) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:
423) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:
774) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.jav
a:666) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[20:54:51 INFO]: [MultiRobot] Disabling MultiRobot v1.2.0
[20:54:51 INFO]: [MultiRobot] 关闭中...
[20:54:51 INFO]: Red_zhz: Reload complete.
[20:54:51 INFO]: Timings Reset
[20:54:51 INFO]: [Yum] [Yum 网络管理] 插件 VexView 尝试访问网络 请注意服务器网络
安全!
[20:54:51 INFO]: [Yum] [Yum 网络管理] 地址: https://lk520.coding.me/VexView/upda
te.txt
[20:54:52 WARN]: Exception in thread " Connect thread for 47.104.212.33:42244" j
ava.lang.IllegalStateException: zip file closed
[20:54:52 WARN]:        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:669)
[20:54:52 WARN]:        at java.util.zip.ZipFile.getEntry(ZipFile.java:309)
[20:54:52 WARN]:        at java.util.jar.JarFile.getEntry(JarFile.java:240)
[20:54:52 WARN]:        at java.util.jar.JarFile.getJarEntry(JarFile.java:223)
[20:54:52 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(Pl
uginClassLoader.java:120)
[20:54:52 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(Pl
uginClassLoader.java:104)
[20:54:52 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

[20:54:52 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

[20:54:52 WARN]:        at com.xuhao.didi.socket.client.impl.client.action.Actio
nDispatcher.sendBroadcast(ActionDispatcher.java:191)
[20:54:52 WARN]:        at com.xuhao.didi.socket.client.impl.client.AbsConnectio
nManager.sendBroadcast(AbsConnectionManager.java:56)
[20:54:52 WARN]:        at com.xuhao.didi.socket.client.impl.client.ConnectionMa
nagerImpl$ConnectionThread.run(ConnectionManagerImpl.java:212)
[20:54:52 INFO]: 仓库: Yum官方仓库 更新成功!
```
这是我加载时的报错。。

**Comment by ExerciseBook** [comment]
已更新版本。本issue暂时关闭。感谢支持。
