### ISSUE TITLE
查看图片时报错

### ISSUE THREAD

**Issue by HuanCheng65** [ParaParty/JustChat#19]
**描述这个错误**
点击提示“An internal error occurred while attempting to perform this command”
后台报错：
```
org.bukkit.command.CommandException: Unhandled exception executing command 'getimage' in plugin MultiRobot v1.2.0
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:git-Akarin-"7487ac4"]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[SimpleCommandMap.class:git-Akarin-"7487ac4"]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:688) ~[CraftServer.class:git-Akarin-"7487ac4"]
at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1494) ~[PlayerConnection.class:git-Akarin-"7487ac4"]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1296) ~[PlayerConnection.class:git-Akarin-"7487ac4"]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[PacketPlayInChat.class:git-Akarin-"7487ac4"]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[PacketPlayInChat.class:git-Akarin-"7487ac4"]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.mde34b36$lambda$ensureMainThread$0$0(PlayerConnectionUtils.java:523) ~[PlayerConnectionUtils.class:git-Akarin-"7487ac4"]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:1921) ~[MinecraftServer.class:git-Akarin-"7487ac4"]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[DedicatedServer.class:git-Akarin-"7487ac4"]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[MinecraftServer.class:git-Akarin-"7487ac4"]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[MinecraftServer.class:git-Akarin-"7487ac4"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.lang.NullPointerException
at cn.endymx.multirobot.vexview.VexView.zoomImage(VexView.java:32) ~[?:?]
at cn.endymx.multirobot.vexview.VexView.sendHUD(VexView.java:23) ~[?:?]
at cn.endymx.multirobot.LoadClass.onCommand(LoadClass.java:89) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:git-Akarin-"7487ac4"]
... 12 more
```

**复现**
通过以下的操作可以产生这个错误:
点击任意一条带图片消息中的图片均会出现此错误

**期望的运行结果**
正常显示图片

**作业平台 (请务必完善本栏内容):**
1. 第一作业平台
	- 操作系统: Unknown
	- 运行平台: Akarin version git-Akarin-"7487ac4" (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
	- 插件版本: 1.2.0
2. 第二作业平台
	- 操作系统: CentOS 7.7
	- 运行平台: CoolQ Air
	- 插件版本: 1.2.1

**Comment by ExerciseBook** [comment]
了解，感谢提交错误信息。

**Comment by endymx** [comment]
是VV版本更新导致的BUG，现在VV作者停更，观望新的插件中
